// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcRequestHeaderProto.proto

package com.RpcRequestHeaderProto;

public final class RpcRequestHeaderProtobuf {
  private RpcRequestHeaderProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code RpcKindProto}
   */
  public enum RpcKindProto
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RPC_BUILTIN = 0;</code>
     *
     * <pre>
     * Used for built in calls by tests
     * </pre>
     */
    RPC_BUILTIN(0, 0),
    /**
     * <code>RPC_WRITABLE = 1;</code>
     *
     * <pre>
     * Use WritableRpcEngine 
     * </pre>
     */
    RPC_WRITABLE(1, 1),
    /**
     * <code>RPC_PROTOCOL_BUFFER = 2;</code>
     *
     * <pre>
     * Use ProtobufRpcEngine
     * </pre>
     */
    RPC_PROTOCOL_BUFFER(2, 2),
    ;

    /**
     * <code>RPC_BUILTIN = 0;</code>
     *
     * <pre>
     * Used for built in calls by tests
     * </pre>
     */
    public static final int RPC_BUILTIN_VALUE = 0;
    /**
     * <code>RPC_WRITABLE = 1;</code>
     *
     * <pre>
     * Use WritableRpcEngine 
     * </pre>
     */
    public static final int RPC_WRITABLE_VALUE = 1;
    /**
     * <code>RPC_PROTOCOL_BUFFER = 2;</code>
     *
     * <pre>
     * Use ProtobufRpcEngine
     * </pre>
     */
    public static final int RPC_PROTOCOL_BUFFER_VALUE = 2;


    public final int getNumber() { return value; }

    public static RpcKindProto valueOf(int value) {
      switch (value) {
        case 0: return RPC_BUILTIN;
        case 1: return RPC_WRITABLE;
        case 2: return RPC_PROTOCOL_BUFFER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RpcKindProto>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RpcKindProto>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RpcKindProto>() {
            public RpcKindProto findValueByNumber(int number) {
              return RpcKindProto.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.getDescriptor().getEnumTypes().get(0);
    }

    private static final RpcKindProto[] VALUES = values();

    public static RpcKindProto valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private RpcKindProto(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RpcKindProto)
  }

  public interface RpcRequestHeaderProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .RpcKindProto rpcKind = 1;
    /**
     * <code>optional .RpcKindProto rpcKind = 1;</code>
     */
    boolean hasRpcKind();
    /**
     * <code>optional .RpcKindProto rpcKind = 1;</code>
     */
    com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcKindProto getRpcKind();

    // optional .RpcRequestHeaderProto.OperationProto rpcOp = 2;
    /**
     * <code>optional .RpcRequestHeaderProto.OperationProto rpcOp = 2;</code>
     */
    boolean hasRpcOp();
    /**
     * <code>optional .RpcRequestHeaderProto.OperationProto rpcOp = 2;</code>
     */
    com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.OperationProto getRpcOp();

    // required sint32 callId = 3;
    /**
     * <code>required sint32 callId = 3;</code>
     *
     * <pre>
     * a sequence number that is sent back in response
     * </pre>
     */
    boolean hasCallId();
    /**
     * <code>required sint32 callId = 3;</code>
     *
     * <pre>
     * a sequence number that is sent back in response
     * </pre>
     */
    int getCallId();

    // required bytes clientId = 4;
    /**
     * <code>required bytes clientId = 4;</code>
     *
     * <pre>
     * Globally unique client ID
     * </pre>
     */
    boolean hasClientId();
    /**
     * <code>required bytes clientId = 4;</code>
     *
     * <pre>
     * Globally unique client ID
     * </pre>
     */
    com.google.protobuf.ByteString getClientId();

    // optional sint32 retryCount = 5 [default = -1];
    /**
     * <code>optional sint32 retryCount = 5 [default = -1];</code>
     *
     * <pre>
     * clientId + callId uniquely identifies a request
     * retry count, 1 means this is the first retry
     * </pre>
     */
    boolean hasRetryCount();
    /**
     * <code>optional sint32 retryCount = 5 [default = -1];</code>
     *
     * <pre>
     * clientId + callId uniquely identifies a request
     * retry count, 1 means this is the first retry
     * </pre>
     */
    int getRetryCount();

    // optional .RPCTraceInfoProto traceInfo = 6;
    /**
     * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
     *
     * <pre>
     * tracing info
     * </pre>
     */
    boolean hasTraceInfo();
    /**
     * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
     *
     * <pre>
     * tracing info
     * </pre>
     */
    com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto getTraceInfo();
    /**
     * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
     *
     * <pre>
     * tracing info
     * </pre>
     */
    com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProtoOrBuilder getTraceInfoOrBuilder();

    // optional .RPCCallerContextProto callerContext = 7;
    /**
     * <code>optional .RPCCallerContextProto callerContext = 7;</code>
     *
     * <pre>
     * call context
     * </pre>
     */
    boolean hasCallerContext();
    /**
     * <code>optional .RPCCallerContextProto callerContext = 7;</code>
     *
     * <pre>
     * call context
     * </pre>
     */
    com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto getCallerContext();
    /**
     * <code>optional .RPCCallerContextProto callerContext = 7;</code>
     *
     * <pre>
     * call context
     * </pre>
     */
    com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProtoOrBuilder getCallerContextOrBuilder();
  }
  /**
   * Protobuf type {@code RpcRequestHeaderProto}
   *
   * <pre>
   * the header for the RpcRequest
   * </pre>
   */
  public static final class RpcRequestHeaderProto extends
      com.google.protobuf.GeneratedMessage
      implements RpcRequestHeaderProtoOrBuilder {
    // Use RpcRequestHeaderProto.newBuilder() to construct.
    private RpcRequestHeaderProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcRequestHeaderProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcRequestHeaderProto defaultInstance;
    public static RpcRequestHeaderProto getDefaultInstance() {
      return defaultInstance;
    }

    public RpcRequestHeaderProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcRequestHeaderProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcKindProto value = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcKindProto.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                rpcKind_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.OperationProto value = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.OperationProto.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                rpcOp_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              callId_ = input.readSInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              clientId_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              retryCount_ = input.readSInt32();
              break;
            }
            case 50: {
              com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = traceInfo_.toBuilder();
              }
              traceInfo_ = input.readMessage(com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(traceInfo_);
                traceInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 58: {
              com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = callerContext_.toBuilder();
              }
              callerContext_ = input.readMessage(com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(callerContext_);
                callerContext_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RpcRequestHeaderProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RpcRequestHeaderProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.class, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcRequestHeaderProto> PARSER =
        new com.google.protobuf.AbstractParser<RpcRequestHeaderProto>() {
      public RpcRequestHeaderProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcRequestHeaderProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcRequestHeaderProto> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code RpcRequestHeaderProto.OperationProto}
     */
    public enum OperationProto
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RPC_FINAL_PACKET = 0;</code>
       *
       * <pre>
       * The final RPC Packet
       * </pre>
       */
      RPC_FINAL_PACKET(0, 0),
      /**
       * <code>RPC_CONTINUATION_PACKET = 1;</code>
       *
       * <pre>
       * not implemented yet
       * </pre>
       */
      RPC_CONTINUATION_PACKET(1, 1),
      /**
       * <code>RPC_CLOSE_CONNECTION = 2;</code>
       *
       * <pre>
       * close the rpc connection
       * </pre>
       */
      RPC_CLOSE_CONNECTION(2, 2),
      ;

      /**
       * <code>RPC_FINAL_PACKET = 0;</code>
       *
       * <pre>
       * The final RPC Packet
       * </pre>
       */
      public static final int RPC_FINAL_PACKET_VALUE = 0;
      /**
       * <code>RPC_CONTINUATION_PACKET = 1;</code>
       *
       * <pre>
       * not implemented yet
       * </pre>
       */
      public static final int RPC_CONTINUATION_PACKET_VALUE = 1;
      /**
       * <code>RPC_CLOSE_CONNECTION = 2;</code>
       *
       * <pre>
       * close the rpc connection
       * </pre>
       */
      public static final int RPC_CLOSE_CONNECTION_VALUE = 2;


      public final int getNumber() { return value; }

      public static OperationProto valueOf(int value) {
        switch (value) {
          case 0: return RPC_FINAL_PACKET;
          case 1: return RPC_CONTINUATION_PACKET;
          case 2: return RPC_CLOSE_CONNECTION;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<OperationProto>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<OperationProto>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OperationProto>() {
              public OperationProto findValueByNumber(int number) {
                return OperationProto.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.getDescriptor().getEnumTypes().get(0);
      }

      private static final OperationProto[] VALUES = values();

      public static OperationProto valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private OperationProto(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RpcRequestHeaderProto.OperationProto)
    }

    private int bitField0_;
    // optional .RpcKindProto rpcKind = 1;
    public static final int RPCKIND_FIELD_NUMBER = 1;
    private com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcKindProto rpcKind_;
    /**
     * <code>optional .RpcKindProto rpcKind = 1;</code>
     */
    public boolean hasRpcKind() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .RpcKindProto rpcKind = 1;</code>
     */
    public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcKindProto getRpcKind() {
      return rpcKind_;
    }

    // optional .RpcRequestHeaderProto.OperationProto rpcOp = 2;
    public static final int RPCOP_FIELD_NUMBER = 2;
    private com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.OperationProto rpcOp_;
    /**
     * <code>optional .RpcRequestHeaderProto.OperationProto rpcOp = 2;</code>
     */
    public boolean hasRpcOp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .RpcRequestHeaderProto.OperationProto rpcOp = 2;</code>
     */
    public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.OperationProto getRpcOp() {
      return rpcOp_;
    }

    // required sint32 callId = 3;
    public static final int CALLID_FIELD_NUMBER = 3;
    private int callId_;
    /**
     * <code>required sint32 callId = 3;</code>
     *
     * <pre>
     * a sequence number that is sent back in response
     * </pre>
     */
    public boolean hasCallId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required sint32 callId = 3;</code>
     *
     * <pre>
     * a sequence number that is sent back in response
     * </pre>
     */
    public int getCallId() {
      return callId_;
    }

    // required bytes clientId = 4;
    public static final int CLIENTID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString clientId_;
    /**
     * <code>required bytes clientId = 4;</code>
     *
     * <pre>
     * Globally unique client ID
     * </pre>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes clientId = 4;</code>
     *
     * <pre>
     * Globally unique client ID
     * </pre>
     */
    public com.google.protobuf.ByteString getClientId() {
      return clientId_;
    }

    // optional sint32 retryCount = 5 [default = -1];
    public static final int RETRYCOUNT_FIELD_NUMBER = 5;
    private int retryCount_;
    /**
     * <code>optional sint32 retryCount = 5 [default = -1];</code>
     *
     * <pre>
     * clientId + callId uniquely identifies a request
     * retry count, 1 means this is the first retry
     * </pre>
     */
    public boolean hasRetryCount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional sint32 retryCount = 5 [default = -1];</code>
     *
     * <pre>
     * clientId + callId uniquely identifies a request
     * retry count, 1 means this is the first retry
     * </pre>
     */
    public int getRetryCount() {
      return retryCount_;
    }

    // optional .RPCTraceInfoProto traceInfo = 6;
    public static final int TRACEINFO_FIELD_NUMBER = 6;
    private com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto traceInfo_;
    /**
     * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
     *
     * <pre>
     * tracing info
     * </pre>
     */
    public boolean hasTraceInfo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
     *
     * <pre>
     * tracing info
     * </pre>
     */
    public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto getTraceInfo() {
      return traceInfo_;
    }
    /**
     * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
     *
     * <pre>
     * tracing info
     * </pre>
     */
    public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProtoOrBuilder getTraceInfoOrBuilder() {
      return traceInfo_;
    }

    // optional .RPCCallerContextProto callerContext = 7;
    public static final int CALLERCONTEXT_FIELD_NUMBER = 7;
    private com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto callerContext_;
    /**
     * <code>optional .RPCCallerContextProto callerContext = 7;</code>
     *
     * <pre>
     * call context
     * </pre>
     */
    public boolean hasCallerContext() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .RPCCallerContextProto callerContext = 7;</code>
     *
     * <pre>
     * call context
     * </pre>
     */
    public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto getCallerContext() {
      return callerContext_;
    }
    /**
     * <code>optional .RPCCallerContextProto callerContext = 7;</code>
     *
     * <pre>
     * call context
     * </pre>
     */
    public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProtoOrBuilder getCallerContextOrBuilder() {
      return callerContext_;
    }

    private void initFields() {
      rpcKind_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcKindProto.RPC_BUILTIN;
      rpcOp_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.OperationProto.RPC_FINAL_PACKET;
      callId_ = 0;
      clientId_ = com.google.protobuf.ByteString.EMPTY;
      retryCount_ = -1;
      traceInfo_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.getDefaultInstance();
      callerContext_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCallId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasCallerContext()) {
        if (!getCallerContext().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, rpcKind_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, rpcOp_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, callId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, clientId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeSInt32(5, retryCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, traceInfo_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, callerContext_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, rpcKind_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, rpcOp_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, callId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, clientId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(5, retryCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, traceInfo_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, callerContext_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RpcRequestHeaderProto}
     *
     * <pre>
     * the header for the RpcRequest
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RpcRequestHeaderProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RpcRequestHeaderProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.class, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.Builder.class);
      }

      // Construct using com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTraceInfoFieldBuilder();
          getCallerContextFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rpcKind_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcKindProto.RPC_BUILTIN;
        bitField0_ = (bitField0_ & ~0x00000001);
        rpcOp_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.OperationProto.RPC_FINAL_PACKET;
        bitField0_ = (bitField0_ & ~0x00000002);
        callId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        clientId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        retryCount_ = -1;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (traceInfoBuilder_ == null) {
          traceInfo_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.getDefaultInstance();
        } else {
          traceInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (callerContextBuilder_ == null) {
          callerContext_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.getDefaultInstance();
        } else {
          callerContextBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RpcRequestHeaderProto_descriptor;
      }

      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto getDefaultInstanceForType() {
        return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.getDefaultInstance();
      }

      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto build() {
        com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto buildPartial() {
        com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto result = new com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rpcKind_ = rpcKind_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rpcOp_ = rpcOp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.callId_ = callId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.retryCount_ = retryCount_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (traceInfoBuilder_ == null) {
          result.traceInfo_ = traceInfo_;
        } else {
          result.traceInfo_ = traceInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (callerContextBuilder_ == null) {
          result.callerContext_ = callerContext_;
        } else {
          result.callerContext_ = callerContextBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto) {
          return mergeFrom((com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto other) {
        if (other == com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.getDefaultInstance()) return this;
        if (other.hasRpcKind()) {
          setRpcKind(other.getRpcKind());
        }
        if (other.hasRpcOp()) {
          setRpcOp(other.getRpcOp());
        }
        if (other.hasCallId()) {
          setCallId(other.getCallId());
        }
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasRetryCount()) {
          setRetryCount(other.getRetryCount());
        }
        if (other.hasTraceInfo()) {
          mergeTraceInfo(other.getTraceInfo());
        }
        if (other.hasCallerContext()) {
          mergeCallerContext(other.getCallerContext());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCallId()) {
          
          return false;
        }
        if (!hasClientId()) {
          
          return false;
        }
        if (hasCallerContext()) {
          if (!getCallerContext().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .RpcKindProto rpcKind = 1;
      private com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcKindProto rpcKind_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcKindProto.RPC_BUILTIN;
      /**
       * <code>optional .RpcKindProto rpcKind = 1;</code>
       */
      public boolean hasRpcKind() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .RpcKindProto rpcKind = 1;</code>
       */
      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcKindProto getRpcKind() {
        return rpcKind_;
      }
      /**
       * <code>optional .RpcKindProto rpcKind = 1;</code>
       */
      public Builder setRpcKind(com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcKindProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        rpcKind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .RpcKindProto rpcKind = 1;</code>
       */
      public Builder clearRpcKind() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rpcKind_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcKindProto.RPC_BUILTIN;
        onChanged();
        return this;
      }

      // optional .RpcRequestHeaderProto.OperationProto rpcOp = 2;
      private com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.OperationProto rpcOp_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.OperationProto.RPC_FINAL_PACKET;
      /**
       * <code>optional .RpcRequestHeaderProto.OperationProto rpcOp = 2;</code>
       */
      public boolean hasRpcOp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .RpcRequestHeaderProto.OperationProto rpcOp = 2;</code>
       */
      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.OperationProto getRpcOp() {
        return rpcOp_;
      }
      /**
       * <code>optional .RpcRequestHeaderProto.OperationProto rpcOp = 2;</code>
       */
      public Builder setRpcOp(com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.OperationProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        rpcOp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .RpcRequestHeaderProto.OperationProto rpcOp = 2;</code>
       */
      public Builder clearRpcOp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rpcOp_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RpcRequestHeaderProto.OperationProto.RPC_FINAL_PACKET;
        onChanged();
        return this;
      }

      // required sint32 callId = 3;
      private int callId_ ;
      /**
       * <code>required sint32 callId = 3;</code>
       *
       * <pre>
       * a sequence number that is sent back in response
       * </pre>
       */
      public boolean hasCallId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required sint32 callId = 3;</code>
       *
       * <pre>
       * a sequence number that is sent back in response
       * </pre>
       */
      public int getCallId() {
        return callId_;
      }
      /**
       * <code>required sint32 callId = 3;</code>
       *
       * <pre>
       * a sequence number that is sent back in response
       * </pre>
       */
      public Builder setCallId(int value) {
        bitField0_ |= 0x00000004;
        callId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 callId = 3;</code>
       *
       * <pre>
       * a sequence number that is sent back in response
       * </pre>
       */
      public Builder clearCallId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        callId_ = 0;
        onChanged();
        return this;
      }

      // required bytes clientId = 4;
      private com.google.protobuf.ByteString clientId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes clientId = 4;</code>
       *
       * <pre>
       * Globally unique client ID
       * </pre>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes clientId = 4;</code>
       *
       * <pre>
       * Globally unique client ID
       * </pre>
       */
      public com.google.protobuf.ByteString getClientId() {
        return clientId_;
      }
      /**
       * <code>required bytes clientId = 4;</code>
       *
       * <pre>
       * Globally unique client ID
       * </pre>
       */
      public Builder setClientId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes clientId = 4;</code>
       *
       * <pre>
       * Globally unique client ID
       * </pre>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }

      // optional sint32 retryCount = 5 [default = -1];
      private int retryCount_ = -1;
      /**
       * <code>optional sint32 retryCount = 5 [default = -1];</code>
       *
       * <pre>
       * clientId + callId uniquely identifies a request
       * retry count, 1 means this is the first retry
       * </pre>
       */
      public boolean hasRetryCount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional sint32 retryCount = 5 [default = -1];</code>
       *
       * <pre>
       * clientId + callId uniquely identifies a request
       * retry count, 1 means this is the first retry
       * </pre>
       */
      public int getRetryCount() {
        return retryCount_;
      }
      /**
       * <code>optional sint32 retryCount = 5 [default = -1];</code>
       *
       * <pre>
       * clientId + callId uniquely identifies a request
       * retry count, 1 means this is the first retry
       * </pre>
       */
      public Builder setRetryCount(int value) {
        bitField0_ |= 0x00000010;
        retryCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 retryCount = 5 [default = -1];</code>
       *
       * <pre>
       * clientId + callId uniquely identifies a request
       * retry count, 1 means this is the first retry
       * </pre>
       */
      public Builder clearRetryCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        retryCount_ = -1;
        onChanged();
        return this;
      }

      // optional .RPCTraceInfoProto traceInfo = 6;
      private com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto traceInfo_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.Builder, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProtoOrBuilder> traceInfoBuilder_;
      /**
       * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
       *
       * <pre>
       * tracing info
       * </pre>
       */
      public boolean hasTraceInfo() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
       *
       * <pre>
       * tracing info
       * </pre>
       */
      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto getTraceInfo() {
        if (traceInfoBuilder_ == null) {
          return traceInfo_;
        } else {
          return traceInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
       *
       * <pre>
       * tracing info
       * </pre>
       */
      public Builder setTraceInfo(com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto value) {
        if (traceInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          traceInfo_ = value;
          onChanged();
        } else {
          traceInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
       *
       * <pre>
       * tracing info
       * </pre>
       */
      public Builder setTraceInfo(
          com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.Builder builderForValue) {
        if (traceInfoBuilder_ == null) {
          traceInfo_ = builderForValue.build();
          onChanged();
        } else {
          traceInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
       *
       * <pre>
       * tracing info
       * </pre>
       */
      public Builder mergeTraceInfo(com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto value) {
        if (traceInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              traceInfo_ != com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.getDefaultInstance()) {
            traceInfo_ =
              com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.newBuilder(traceInfo_).mergeFrom(value).buildPartial();
          } else {
            traceInfo_ = value;
          }
          onChanged();
        } else {
          traceInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
       *
       * <pre>
       * tracing info
       * </pre>
       */
      public Builder clearTraceInfo() {
        if (traceInfoBuilder_ == null) {
          traceInfo_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.getDefaultInstance();
          onChanged();
        } else {
          traceInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
       *
       * <pre>
       * tracing info
       * </pre>
       */
      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.Builder getTraceInfoBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getTraceInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
       *
       * <pre>
       * tracing info
       * </pre>
       */
      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProtoOrBuilder getTraceInfoOrBuilder() {
        if (traceInfoBuilder_ != null) {
          return traceInfoBuilder_.getMessageOrBuilder();
        } else {
          return traceInfo_;
        }
      }
      /**
       * <code>optional .RPCTraceInfoProto traceInfo = 6;</code>
       *
       * <pre>
       * tracing info
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.Builder, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProtoOrBuilder> 
          getTraceInfoFieldBuilder() {
        if (traceInfoBuilder_ == null) {
          traceInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.Builder, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProtoOrBuilder>(
                  traceInfo_,
                  getParentForChildren(),
                  isClean());
          traceInfo_ = null;
        }
        return traceInfoBuilder_;
      }

      // optional .RPCCallerContextProto callerContext = 7;
      private com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto callerContext_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.Builder, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProtoOrBuilder> callerContextBuilder_;
      /**
       * <code>optional .RPCCallerContextProto callerContext = 7;</code>
       *
       * <pre>
       * call context
       * </pre>
       */
      public boolean hasCallerContext() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .RPCCallerContextProto callerContext = 7;</code>
       *
       * <pre>
       * call context
       * </pre>
       */
      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto getCallerContext() {
        if (callerContextBuilder_ == null) {
          return callerContext_;
        } else {
          return callerContextBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .RPCCallerContextProto callerContext = 7;</code>
       *
       * <pre>
       * call context
       * </pre>
       */
      public Builder setCallerContext(com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto value) {
        if (callerContextBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          callerContext_ = value;
          onChanged();
        } else {
          callerContextBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .RPCCallerContextProto callerContext = 7;</code>
       *
       * <pre>
       * call context
       * </pre>
       */
      public Builder setCallerContext(
          com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.Builder builderForValue) {
        if (callerContextBuilder_ == null) {
          callerContext_ = builderForValue.build();
          onChanged();
        } else {
          callerContextBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .RPCCallerContextProto callerContext = 7;</code>
       *
       * <pre>
       * call context
       * </pre>
       */
      public Builder mergeCallerContext(com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto value) {
        if (callerContextBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              callerContext_ != com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.getDefaultInstance()) {
            callerContext_ =
              com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.newBuilder(callerContext_).mergeFrom(value).buildPartial();
          } else {
            callerContext_ = value;
          }
          onChanged();
        } else {
          callerContextBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .RPCCallerContextProto callerContext = 7;</code>
       *
       * <pre>
       * call context
       * </pre>
       */
      public Builder clearCallerContext() {
        if (callerContextBuilder_ == null) {
          callerContext_ = com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.getDefaultInstance();
          onChanged();
        } else {
          callerContextBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .RPCCallerContextProto callerContext = 7;</code>
       *
       * <pre>
       * call context
       * </pre>
       */
      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.Builder getCallerContextBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getCallerContextFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .RPCCallerContextProto callerContext = 7;</code>
       *
       * <pre>
       * call context
       * </pre>
       */
      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProtoOrBuilder getCallerContextOrBuilder() {
        if (callerContextBuilder_ != null) {
          return callerContextBuilder_.getMessageOrBuilder();
        } else {
          return callerContext_;
        }
      }
      /**
       * <code>optional .RPCCallerContextProto callerContext = 7;</code>
       *
       * <pre>
       * call context
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.Builder, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProtoOrBuilder> 
          getCallerContextFieldBuilder() {
        if (callerContextBuilder_ == null) {
          callerContextBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.Builder, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProtoOrBuilder>(
                  callerContext_,
                  getParentForChildren(),
                  isClean());
          callerContext_ = null;
        }
        return callerContextBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:RpcRequestHeaderProto)
    }

    static {
      defaultInstance = new RpcRequestHeaderProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RpcRequestHeaderProto)
  }

  public interface RPCTraceInfoProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 traceId = 1;
    /**
     * <code>optional int64 traceId = 1;</code>
     *
     * <pre>
     * parentIdHigh
     * </pre>
     */
    boolean hasTraceId();
    /**
     * <code>optional int64 traceId = 1;</code>
     *
     * <pre>
     * parentIdHigh
     * </pre>
     */
    long getTraceId();

    // optional int64 parentId = 2;
    /**
     * <code>optional int64 parentId = 2;</code>
     *
     * <pre>
     * parentIdLow
     * </pre>
     */
    boolean hasParentId();
    /**
     * <code>optional int64 parentId = 2;</code>
     *
     * <pre>
     * parentIdLow
     * </pre>
     */
    long getParentId();
  }
  /**
   * Protobuf type {@code RPCTraceInfoProto}
   */
  public static final class RPCTraceInfoProto extends
      com.google.protobuf.GeneratedMessage
      implements RPCTraceInfoProtoOrBuilder {
    // Use RPCTraceInfoProto.newBuilder() to construct.
    private RPCTraceInfoProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RPCTraceInfoProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RPCTraceInfoProto defaultInstance;
    public static RPCTraceInfoProto getDefaultInstance() {
      return defaultInstance;
    }

    public RPCTraceInfoProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RPCTraceInfoProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              traceId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              parentId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RPCTraceInfoProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RPCTraceInfoProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.class, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.Builder.class);
    }

    public static com.google.protobuf.Parser<RPCTraceInfoProto> PARSER =
        new com.google.protobuf.AbstractParser<RPCTraceInfoProto>() {
      public RPCTraceInfoProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RPCTraceInfoProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RPCTraceInfoProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 traceId = 1;
    public static final int TRACEID_FIELD_NUMBER = 1;
    private long traceId_;
    /**
     * <code>optional int64 traceId = 1;</code>
     *
     * <pre>
     * parentIdHigh
     * </pre>
     */
    public boolean hasTraceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 traceId = 1;</code>
     *
     * <pre>
     * parentIdHigh
     * </pre>
     */
    public long getTraceId() {
      return traceId_;
    }

    // optional int64 parentId = 2;
    public static final int PARENTID_FIELD_NUMBER = 2;
    private long parentId_;
    /**
     * <code>optional int64 parentId = 2;</code>
     *
     * <pre>
     * parentIdLow
     * </pre>
     */
    public boolean hasParentId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 parentId = 2;</code>
     *
     * <pre>
     * parentIdLow
     * </pre>
     */
    public long getParentId() {
      return parentId_;
    }

    private void initFields() {
      traceId_ = 0L;
      parentId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, traceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, parentId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, traceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, parentId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RPCTraceInfoProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RPCTraceInfoProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RPCTraceInfoProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.class, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.Builder.class);
      }

      // Construct using com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        traceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        parentId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RPCTraceInfoProto_descriptor;
      }

      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto getDefaultInstanceForType() {
        return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.getDefaultInstance();
      }

      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto build() {
        com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto buildPartial() {
        com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto result = new com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.traceId_ = traceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.parentId_ = parentId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto) {
          return mergeFrom((com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto other) {
        if (other == com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto.getDefaultInstance()) return this;
        if (other.hasTraceId()) {
          setTraceId(other.getTraceId());
        }
        if (other.hasParentId()) {
          setParentId(other.getParentId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCTraceInfoProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 traceId = 1;
      private long traceId_ ;
      /**
       * <code>optional int64 traceId = 1;</code>
       *
       * <pre>
       * parentIdHigh
       * </pre>
       */
      public boolean hasTraceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 traceId = 1;</code>
       *
       * <pre>
       * parentIdHigh
       * </pre>
       */
      public long getTraceId() {
        return traceId_;
      }
      /**
       * <code>optional int64 traceId = 1;</code>
       *
       * <pre>
       * parentIdHigh
       * </pre>
       */
      public Builder setTraceId(long value) {
        bitField0_ |= 0x00000001;
        traceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 traceId = 1;</code>
       *
       * <pre>
       * parentIdHigh
       * </pre>
       */
      public Builder clearTraceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        traceId_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 parentId = 2;
      private long parentId_ ;
      /**
       * <code>optional int64 parentId = 2;</code>
       *
       * <pre>
       * parentIdLow
       * </pre>
       */
      public boolean hasParentId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 parentId = 2;</code>
       *
       * <pre>
       * parentIdLow
       * </pre>
       */
      public long getParentId() {
        return parentId_;
      }
      /**
       * <code>optional int64 parentId = 2;</code>
       *
       * <pre>
       * parentIdLow
       * </pre>
       */
      public Builder setParentId(long value) {
        bitField0_ |= 0x00000002;
        parentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 parentId = 2;</code>
       *
       * <pre>
       * parentIdLow
       * </pre>
       */
      public Builder clearParentId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parentId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RPCTraceInfoProto)
    }

    static {
      defaultInstance = new RPCTraceInfoProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RPCTraceInfoProto)
  }

  public interface RPCCallerContextProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string context = 1;
    /**
     * <code>required string context = 1;</code>
     */
    boolean hasContext();
    /**
     * <code>required string context = 1;</code>
     */
    java.lang.String getContext();
    /**
     * <code>required string context = 1;</code>
     */
    com.google.protobuf.ByteString
        getContextBytes();

    // optional bytes signature = 2;
    /**
     * <code>optional bytes signature = 2;</code>
     */
    boolean hasSignature();
    /**
     * <code>optional bytes signature = 2;</code>
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code RPCCallerContextProto}
   */
  public static final class RPCCallerContextProto extends
      com.google.protobuf.GeneratedMessage
      implements RPCCallerContextProtoOrBuilder {
    // Use RPCCallerContextProto.newBuilder() to construct.
    private RPCCallerContextProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RPCCallerContextProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RPCCallerContextProto defaultInstance;
    public static RPCCallerContextProto getDefaultInstance() {
      return defaultInstance;
    }

    public RPCCallerContextProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RPCCallerContextProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              context_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              signature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RPCCallerContextProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RPCCallerContextProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.class, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.Builder.class);
    }

    public static com.google.protobuf.Parser<RPCCallerContextProto> PARSER =
        new com.google.protobuf.AbstractParser<RPCCallerContextProto>() {
      public RPCCallerContextProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RPCCallerContextProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RPCCallerContextProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string context = 1;
    public static final int CONTEXT_FIELD_NUMBER = 1;
    private java.lang.Object context_;
    /**
     * <code>required string context = 1;</code>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string context = 1;</code>
     */
    public java.lang.String getContext() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          context_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string context = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes signature = 2;
    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>optional bytes signature = 2;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes signature = 2;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private void initFields() {
      context_ = "";
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasContext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, signature_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getContextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RPCCallerContextProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RPCCallerContextProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RPCCallerContextProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.class, com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.Builder.class);
      }

      // Construct using com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        context_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        signature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.internal_static_RPCCallerContextProto_descriptor;
      }

      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto getDefaultInstanceForType() {
        return com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.getDefaultInstance();
      }

      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto build() {
        com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto buildPartial() {
        com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto result = new com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.context_ = context_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.signature_ = signature_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto) {
          return mergeFrom((com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto other) {
        if (other == com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto.getDefaultInstance()) return this;
        if (other.hasContext()) {
          bitField0_ |= 0x00000001;
          context_ = other.context_;
          onChanged();
        }
        if (other.hasSignature()) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContext()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.RpcRequestHeaderProto.RpcRequestHeaderProtobuf.RPCCallerContextProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string context = 1;
      private java.lang.Object context_ = "";
      /**
       * <code>required string context = 1;</code>
       */
      public boolean hasContext() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string context = 1;</code>
       */
      public java.lang.String getContext() {
        java.lang.Object ref = context_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          context_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string context = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContextBytes() {
        java.lang.Object ref = context_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          context_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder setContext(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        context_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000001);
        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder setContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        context_ = value;
        onChanged();
        return this;
      }

      // optional bytes signature = 2;
      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes signature = 2;</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes signature = 2;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>optional bytes signature = 2;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes signature = 2;</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RPCCallerContextProto)
    }

    static {
      defaultInstance = new RPCCallerContextProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RPCCallerContextProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RpcRequestHeaderProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RpcRequestHeaderProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RPCTraceInfoProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RPCTraceInfoProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RPCCallerContextProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RPCCallerContextProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033RpcRequestHeaderProto.proto\"\334\002\n\025RpcReq" +
      "uestHeaderProto\022\036\n\007rpcKind\030\001 \001(\0162\r.RpcKi" +
      "ndProto\0224\n\005rpcOp\030\002 \001(\0162%.RpcRequestHeade" +
      "rProto.OperationProto\022\016\n\006callId\030\003 \002(\021\022\020\n" +
      "\010clientId\030\004 \002(\014\022\026\n\nretryCount\030\005 \001(\021:\002-1\022" +
      "%\n\ttraceInfo\030\006 \001(\0132\022.RPCTraceInfoProto\022-" +
      "\n\rcallerContext\030\007 \001(\0132\026.RPCCallerContext" +
      "Proto\"]\n\016OperationProto\022\024\n\020RPC_FINAL_PAC" +
      "KET\020\000\022\033\n\027RPC_CONTINUATION_PACKET\020\001\022\030\n\024RP" +
      "C_CLOSE_CONNECTION\020\002\"6\n\021RPCTraceInfoProt",
      "o\022\017\n\007traceId\030\001 \001(\003\022\020\n\010parentId\030\002 \001(\003\";\n\025" +
      "RPCCallerContextProto\022\017\n\007context\030\001 \002(\t\022\021" +
      "\n\tsignature\030\002 \001(\014*J\n\014RpcKindProto\022\017\n\013RPC" +
      "_BUILTIN\020\000\022\020\n\014RPC_WRITABLE\020\001\022\027\n\023RPC_PROT" +
      "OCOL_BUFFER\020\002B5\n\031com.RpcRequestHeaderPro" +
      "toB\030RpcRequestHeaderProtobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RpcRequestHeaderProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RpcRequestHeaderProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RpcRequestHeaderProto_descriptor,
              new java.lang.String[] { "RpcKind", "RpcOp", "CallId", "ClientId", "RetryCount", "TraceInfo", "CallerContext", });
          internal_static_RPCTraceInfoProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RPCTraceInfoProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RPCTraceInfoProto_descriptor,
              new java.lang.String[] { "TraceId", "ParentId", });
          internal_static_RPCCallerContextProto_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_RPCCallerContextProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RPCCallerContextProto_descriptor,
              new java.lang.String[] { "Context", "Signature", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
